In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('smart_meter_ami_dataset.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Meter_ID        1200 non-null   object
 1   Timestamp       1200 non-null   object
 2   Energy_kWh      1140 non-null   float64
 3   Voltage_V       1125 non-null   float64
 4   Peak_Demand_kW  1200 non-null   float64
 5   Status          1200 non-null   object
dtypes: float64(3), object(3)
memory usage: 56.4+ KB

In [4]:
df['Meter_ID'].unique()

array(['SM001', 'SM002', 'SM003', 'SM004', 'SM005', 'SM006', 'SM007',
       'SM008', 'SM009', 'SM010'], dtype=object)

In [6]:
df['Status'].unique()

array(['Invalid', 'OK', 'Error', 'Missing', 'Outlier', 'Anomaly'],
      dtype=object)

In [7]:
df.isnull().sum()

Meter_ID           0
Timestamp          0
Energy_kWh        60
Voltage_V         75
Peak_Demand_kW     0
Status             0
dtype: int64

In [8]:
df.shape

(1200, 6)

In [10]:
df.sample(5)

,Meter_ID,Timestamp,Energy_kWh,Voltage_V,Peak_Demand_kW,Status
31,SM001,01-04-2026 07:45,7.76,232.0,10.11,Anomaly
938,SM008,02-04-2026 00:30,1.84,NaN,4.46,Error
1079,SM009,02-04-2026 05:45,-1.27,235.0,3.41,Invalid
274,SM003,01-04-2026 08:30,1.27,235.0,4.34,OK
532,SM005,01-04-2026 13:00,1.52,243.0,3.70,OK

In [11]:
df.describe()

        Energy_kWh    Voltage_V  Peak_Demand_kW
count  1140.000000  1125.000000     1200.000000
mean      1.257035   241.848889        3.844050
std       1.073643    57.078739        1.636912
min      -1.740000   213.000000        2.000000
25%       0.970000   226.000000        3.200000
50%       1.200000   230.000000        3.530000
75%       1.420000   234.000000        3.890000
max       7.760000   500.000000       14.310000

In [12]:
df['Meter_ID'].value_counts()

Meter_ID
SM001    120
SM002    120
SM003    120
SM004    120
SM005    120
SM006    120
SM007    120
SM008    120
SM009    120
SM010    120
Name: count, dtype: int64

In [13]:
df

,Meter_ID,Timestamp,Energy_kWh,Voltage_V,Peak_Demand_kW,Status
0,SM001,01-04-2026 00:00,-1.35,229.0,3.82,Invalid
1,SM001,01-04-2026 00:15,1.66,231.0,4.01,OK
2,SM001,01-04-2026 00:30,1.06,232.0,3.27,OK
3,SM001,01-04-2026 00:45,1.06,216.0,3.98,OK
4,SM001,01-04-2026 01:00,0.90,231.0,3.05,OK
...,...,...,...,...,...,...
1195,SM010,02-04-2026 04:45,1.48,235.0,4.10,OK
1196,SM010,02-04-2026 05:00,1.42,226.0,3.61,OK
1197,SM010,02-04-2026 05:15,1.11,237.0,2.82,OK
1198,SM010,02-04-2026 05:30,0.65,227.0,3.69,OK
1199,SM010,02-04-2026 05:45,1.38,229.0,3.38,OK

In [19]:
from ydata_profiling import ProfileReport

In [21]:
prof = ProfileReport(df)

In [26]:
prof.to_file('output.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [28]:
df[['Energy_kWh','Voltage_V','Peak_Demand_kW']].corr()

                Energy_kWh  Voltage_V  Peak_Demand_kW
Energy_kWh        1.000000   0.009462        0.731229
Voltage_V         0.009462   1.000000       -0.041318
Peak_Demand_kW    0.731229  -0.041318        1.000000